// Writes the licenses of every production dependency bundled into
// web/static/flows/flows.js (the minified bundle drops their notices) to
// web/static/flows/THIRD_PARTY_LICENSES.txt. Runs after `vite build`.
import { execFileSync } from "node:child_process";
import { readFileSync, readdirSync, writeFileSync } from "node:fs";
import { basename, dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const app = join(dirname(fileURLToPath(import.meta.url)), "..");
const out = join(app, "..", "static", "flows", "THIRD_PARTY_LICENSES.txt");

const dirs = execFileSync("npm", ["ls", "--omit=dev", "--all", "--parseable"], { cwd: app, encoding: "utf8" })
  .split("\n").map((line) => line.trim()).filter((line) => line && line !== app);

const entries = [...new Set(dirs)].map((dir) => {
  const pkg = JSON.parse(readFileSync(join(dir, "package.json"), "utf8"));
  const file = readdirSync(dir).find((name) => /^(licen[cs]e|copying)(\.|$)/i.test(name));
  if (!file) throw new Error(`${pkg.name}: no license file in ${dir}`);
  return { name: pkg.name, version: pkg.version, license: pkg.license,
           text: readFileSync(join(dir, file), "utf8").trim() };
}).sort((a, b) => a.name.localeCompare(b.name));

writeFileSync(out, [
  "Third-party software bundled in flows.js and flows.css (the flow builder).",
  "Generated by web/flows-app/scripts/licenses.mjs; do not edit.",
  ...entries.map((e) => `\n${"=".repeat(72)}\n${e.name} ${e.version} (${e.license})\n${"=".repeat(72)}\n\n${e.text}`),
].join("\n") + "\n");
console.log(`${basename(out)}: ${entries.length} packages`);
